#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SlideOverKit.MoreSample.Droid.Resource", IsApplication=true)]

namespace SlideOverKit.MoreSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int About_Blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Battery_Blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Chat_Blue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CommandLine_Blue = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dog = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DoubleDown_Black = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int DoubleDown_Blue = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int DoubleDown_White = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int DoubleLeft = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int DoubleRight = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int DoubleUp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Enter = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Filter_Blue = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Happy = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Home = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Map_Background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MessageFilled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Microphone = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int MoneyBag_Blue = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Pencil = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Report_Blue = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Save_Blue = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Settings = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Timeline_Blue = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int UpIcon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int USBConnected_Color = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int VideoCall = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int xamconsulting = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
